### ISSUE TITLE
Memory Problems: Leaks and Aliasing

### ISSUE THREAD

**Issue by vjackson725** [nickrobson/CPPLists#2]
The way lists are currently defined, it's really easy to loose pointers to memory once you put them in lists.

## Memory Leaks

Consider this example:
```c++
	char* myStr = new char[10];
	list->add(&myStr);
	list->remove(0); //assume this returns myStr
```
Where do we call delete on myStr? We have to call it after remove(0).
But, in this similar example suddenly, we can't delete myStr:
```c++
	{
		char* myStr = new char[10];
		list->add(&myStr);
		... do things here ...
	}
	list->remove(0); //assume this returns myStr
```
When the block closes, the memory is leaked though the list. This issue should be solvable by returning the value that is removed from the list, and leaving it up to the caller to delete it.

## Memory Aliasing

Consider this simple example:
```c++
	int i = 0;
	list->add(&i);
	list->add(&i);
	printf("get(0): %u\n", *static_cast<int*>(list->get(0)));
	printf("get(1): %u\n", *static_cast<int*>(list->get(1)));
	*static_cast<int*>(list->get(0)) = 1;
	printf("get(0): %u\n", *static_cast<int*>(list->get(0)));
	printf("get(1): %u\n", *static_cast<int*>(list->get(1)));
```
In this case, one might expect that modifying list[0] would not effect list[1], but as they're the same pointer, both get modified as such:
```
get(0): 0
get(1): 0
get(0): 1
get(1): 1
```
In this case, it's pretty trivial, and not that terrible, but consider this case:
```c++
	int i = 0;
	list0->add(&i);
	...
	list1.addAll(list0);
	...
	//increment all the numbers in the array
	for(int i = 0; i < list0.size(); i++) {
		*static_cast<int*>(list->get(0))++;
	}
	...
	*static_cast<int*>(list1->get(0)) = -1;
	...
	// what's 0++?
	cout << *static_cast<int*>(list0->get(0)) << endl;
```
As you might guess, this will print -1, which probably isn't intended behaviour.
We have two completely different lists, and the value

**Comment by nickrobson** [comment]
Aye, I see what you mean. The list is not intended to store the values at the pointers; it is intended to store the pointers themselves. It would be holding ints otherwise.

**Comment by nickrobson** [comment]
Oops, thanks mobile site. Anyway, I was going to say that the remove function doesn't return the pointer that was removed; the accessor application is meant to garbage collect that stuff. It just removes it from the list's memory so you don't need to worry about it being present there.
